[preface]
== Preface
Welcome to _Awesome Command Line_!  I am so grateful that you have found this book, and that you're interested in exploring the seemingly secret world of computing from the command line!

This book is a reminder that you have superpowers at your fingertips!  We are all familiar with the ways that we interact with our computers on a daily basis -- _click_, _drag_, _drop_, _scroll_, _touch_, _tap_.  The graphical nature of our screens and applications are absolutely amazing and indispensible.  In this book, we explore the secret little gems available on all operating systems with another familiar way to interact -- _type_!  And the best part is that the magical commands we explore are largely derived from the English words that describe them, so acquainting ourselves with these commands is straight-forward with a bit of guidance.  Once you become familiar with this small set of essential commands, adding new commands to your toolbox is even easier.  With some simple dedication and practice, you will be able to enhance your computing workflow to be even more efficient and powerful.  You'll manage your projects in ways that would otherwise be labor intensive when using your mouse.  The intention of this book is to empower you in your creative journey by showing you how the _command line_ is an awesome tool to get things done!

The UNIX(R) operating system developed by Bell Laboratories in the 1970s and 1980s was groundbreaking technology. When I first learned about _Linux_(R){emdash}a UNIX-inspired operating system for personal computers, I was fascinated by the freedom of it, and spent a substantial amount of time figuring out how to work with it via text commands.  Apple(R) transitioned to a UNIX-like operating system with _Mac OS X_, and Microsoft(R) introduced the Windows(R) Subsystem for Linux to bring a UNIX-like environment to Windows(R).  I've been excited about these moves because we now have access to these incredible tools in very polished desktop environments.  My intention with this book is to save you as much start-up time and energy as possible in learning the command line so you can be as creative as possible on the operating system of your choice, be it _macOS_(R), _Linux_(R), or _Microsoft(R) Windows_(R).  Have fun with it!{empty}footnote:[UNIX is a registered trademark of The Open Group.  Linux is the registered trademark of Linus Torvalds in the U.S. and other countries.  Apple, Mac, and macOS are trademarks of Apple Inc., registered in the U.S. and other countries and regions.  Microsoft and Microsoft Windows are trademarks of the Microsoft group of companies.  References to companies or trademarked products within this work are provided for informational purposes only and do not imply endorsement, sponsorship, or affiliation by those companies. The inclusion of such references is solely for the purpose of illustration or commentary, and the author and publisher do not intend to suggest any formal relationship or approval by the respective trademark holders.]

<<<
[discrete]
=== Who Should Read This Book

This book is written for everyone who loves computing!  It's written as an introductory book to get you started with the infinite universe of text commands.  The twenty one commands that I highlight are essential to building your foundation, and the command line concepts throughout each chapter solidify it further.  This is intended as a launching point for everyone who likes to be organized and productive.  Those in creative works -- _writers_, _artists_, _designers_, _photographers_, and _editors_, and those beginning their journey with computers -- _students_, early career _scientists_, _librarians_, aspiring _engineers_,  _software developers_, _system administrators_, and _project managers_, can all learn the foundations and then pick up the commands that are specific to their course of study, craft, or industry. Those interested in joining the decentralized web by running their own Bitcoin or Lightning node, Nostr relay, and other freedom technologies will benefit from knowing these essentials.  No matter your interests, this book is for those who love to learn!

[discrete]
=== Conventions Used in This Book

The following informational icons are used throughout the book:

[NOTE]
This icon indicates an informational note.

[TIP]
This icon indicates a tip, suggestion, or a point of awesomeness.

[CAUTION]
This icon indicates a time to be very careful with a command or action. It could be irreversible.

[discrete]
=== Getting the Command Line Examples

The examples in this book are accessible for download from a link on the
book release page [{bookurl}].  The entire book source code is released as an open source project under the {license} license, and may be used under those terms.
