[preface]
== Preface
Welcome to _Awesome Command Line_!  I am so grateful that you have found this book, and that you're interested in exploring the seemingly secret world of computing from the command line!

This book is a reminder that you have superpowers at your fingertips!  We are all familiar with the ways that we interact with our computers on a daily basis -- _click_, _drag_, _drop_, _scroll_, _touch_, _tap_.  The graphical nature of our screens and applications are absolutely amazing and indispensible.  In this book, we explore the secret little gems available on all operating systems with another familiar way to interact -- _type_!  And the best part is that the magical commands we explore are largely derived from the English words that describe them, so acquainting ourselves with these commands is straight-forward with a bit of guidance.  Once you become familiar with this small set of essential commands, adding new commands to your toolbox is even easier.  With some simple dedication and practice, you will be able to enhance your computing workflow to be even more efficient and powerful.  You'll manage your projects in ways that would otherwise be labor intensive when using your mouse.  The intention of this book is to empower you in your creative journey by showing you how the _command line_ is an awesome tool to get things done!

When I first learned about the _Linux_(R)footnote:[Linux is the registered trademark of Linus Torvalds in the U.S. and other countries.] operating system, I was fascinated by the freedom of it, and spent a substantial amount of time figuring out how to work with it via text commands.  When Apple(R)footnote:[Apple, Mac, and macOS are trademarks of Apple Inc., registered in the U.S. and other countries and regions.] transitioned to a _UNIX_(R)footnote:[UNIX is a registered trademark of The Open Group.]_-like_ operating system with _Mac OS X_, I was even more excited because I then had access to these tools in a very polished desktop environment.  My intention with this book is to save you that start-up time and energy so you can focus on your creative endeavors with the best tools possible on the operating system of your choice, be it _macOS_(R), _Linux_(R), or _Microsoft(R) Windows_(R)footnote:[Microsoft Windows is a trademark of the Microsoft group of companies.].  Have fun with it!

<<<
[discrete]
=== Who Should Read This Book

This book is written for everyone who wants to expand their computer skills!  It's written as an introductory book to get you started with the infinite universe of text commands.  The twenty one commands that I highlight are essential to building your foundation, and the command line concepts throughout each chapter solidify it further.  This is intended as a launching point for everyone who likes to be organized and productive.  Those in creative works -- _writers_, _artists_, _designers_, _photographers_, and _editors_, and those beginning their journey with computers -- _students_, early career _scientists_, _librarians_, aspiring _engineers_,  _software developers_, _system administrators_, and _project managers_, can all learn the foundations and then pick up the commands that are specific to their course of study, craft, or industry. Likewise, those interested in joining the decentralized web by running their own Bitcoin node, Lightning node, Nostr relay, and other technologies will benefit from knowing the essentials to dive into the world of freedom technology.  No matter your interests, this book is for those who love to learn!

[discrete]
=== Conventions Used in This Book

The following informational icons are used throughout the book:

[NOTE]
This icon indicates an informational note.

[TIP]
This icon indicates a tip, suggestion, or a point of awesomeness.

[CAUTION]
This icon indicates a time to be very careful with a command or action. It could be irreversible.

[discrete]
=== Getting the Command Line Examples

The examples in this book are accessible for download from a link on the
book release page [{bookurl}].  The entire book source code is released as open source under the {license} license, and may be used under those terms.
